const fs = require('fs');

const data = [
  {
    "enunciado": "A Magna Carta assevera o crivo indene atinente à inviolabilidade da manifestação e locomoção. Nesse esteio preceitua em conformidade com o colendo Supremo Tribunal Federal que a excepcionalidade afeta à suspensão ou respectivo denegatório acesso ao instrumento formal acautelatório de cunho heroico denominado por habeas corpus alcança irrestritamente apenas as penalidades contenciosas defrontadas por militares. Sendo assim, no amplo viés afeto de servidores e civis não alistados compulsoriamente e em submissão da administração disciplinar em conselhos normais, a via liberatória em alusão jamais poderá ser extirpada ou mitigada processualmente para rever punições corporais.",
    "options": {
      "c": "Certo",
      "e": "Errado"
    },
    "answer": "c",
    "rationale": "A assertiva alavanca os contornos corretos em conformidade. O artigo 142, parágrafo 2º, preceitua imperativamente e textualmente exclusão restrita de que não caberá a via do habeas corpus unicamente defrontada frente a estritas instâncias em esferas ligadas a correspondentes ''punições disciplinares militares''. O texto não fraciona e não proíbe a via libertária face ao eventual civil e respectiva sindicância. Embora inexista prisão a servidores não militares oriunda da administração pública e haja o repúdio constitucional a referidas fáticas afetas às proibições de tortura, no decurso interpretativo, o HC resguarda e cabe diante punição restritiva à liberdade ambulatorial do cidadão livre.",
    "difficulty": "dificil",
    "tags": ["Habeas Corpus", "Militares", "Punição Disciplinar", "Garantias Constitucionais"]
  },
  {
    "enunciado": "A liberdade associativa na moldura constitucional descredencia qualquer arrimo ou dependência prévia do ato de autorização exarado pelas instâncias governamentais como forma de nascedouro para as agremiações lícitas. Corolário a isso, nos exatos ditames estatuídos na Lei Fundamental garantindo livre reunião pacificamente e sem armas, independentemente inerente de autorização nos amplos recintos abertos e afetos primordialmente e inerentemente em formato público, consubstancia a regra expressa inafastável admitida que apenas é exigida, unicamente em viés procedimental material garantista, a estipulação defrontando eventual pleito afeto que a reunião pretendida jamais frustre por si só anterior convocação no recinto por outra.",
    "options": {
      "c": "Certo",
      "e": "Errado"
    },
    "answer": "c",
    "rationale": "A assertiva apreende o real ditame literal exato. Conforme versa explicitamente a Constituição perante o atinente art. 5º, inciso XVI, em que se lê estipulado peremptoriamente a expressa redação: ''todos podem reunir-se incondicionalmente pacíficos, sem fito de uso envolto a armas, em variados locais contendo prerrogativa de fruição em moldura aberta afeta e inerente a espaços ao viés público, independentemente sem sujeição e refém contendo requerimento perante a respectiva autorização, exigindo-se estritamente e eximiamente perante isso em restrição afeta contendo requisito que por via oblíqua e material não acarrete a funesta e indubitável correspondência e conduta frustrando deliberadamente a diversa idêntica e congênere moldura decorrente convocada anteriormente idêntica no correspondente local''.",
    "difficulty": "dificil",
    "tags": ["Direito de Reunião", "Frustrar Outra Reunião", "Libertades Públicas"]
  },
  {
    "enunciado": "O sigilo é, decerto, exceção contida sob forte primazia de ponderação constitucional. Sob a égide do preceito em alusão à plena transparência republicana inserto firmemente pelo art. 5º, exige-se inafastável viabilização outorgando a imperatividade balizada fornecendo incondicional e amplamente aos postulantes interessados e diretos incondicional amplo acesso voltado frente toda e respectiva integral informação coligida na referendada ordem atinente concernentes ao viés alusivo aos meandros inerentes e próprios da entidade da cúpula estatal e governamental, excepcionando-se e elidindo-se dessa compulsória imposição resoluta com exclusividade unicamente as incontestes matérias restritas afetas de sigilo imprescindível delineadas pela peculiar exigibilidade afetada à insuperável garantia afeta exclusivamente da própria ''segurança nacional soberana e da estabilidade institucional orgânica correspondente ao Estado''.",
    "options": {
      "c": "Certo",
      "e": "Errado"
    },
    "answer": "c",
    "rationale": "A assertiva atesta estrita consonância exata com a baliza preeminente de preceitos fundamentais da transparência. O artigo 5º, no ex vi do seu inciso XXXIII, delineia a premissa de viés abrangente prescrevendo a diretriz exata assegurando categoricamente que todos possuam intrínseco sagrado imperioso direito consubstanciado a receber dos órgãos da instância pública unicamente dados atinentes e de matriz de caráter próprio perante viés de interesse de cariz em nível amplo ou particular e coletivo, sendo tais informações postadas à viabilização prestadas e fornecidas obrigatoriamente sob fulcro sancionatório no prazo, impulsionando elidida a regra imposta eximiamente contendo imperiosa ressalva na resguardada esfera das pontuais contendas em que estrito e irrefutável mantimento protetivo concernente ao sigilo repise imprescindível contundência resguardadora abrigada inafastável à manutenção intrínseca da segurança decorrente face imperiosa da sociedade aglutinada como também precipuamente do Estado Democrático.",
    "difficulty": "dificil",
    "tags": ["Direito à Informação", "Sigilo e Segurança", "Transparência"]
  },
  {
    "enunciado": "O postulado atinente impulsionado perante a liberdade inviolável afeto e regido pelo incondicional primado voltado concernente irrefutavelmente ao mister afeto perante escolhas profissionais perfaz inconteste e primaz desígnio em arrimo outorgado por base constitucional estrita. Dessa maneira basilar preeminente exara a determinação preceituando que ninguém sem escusas seja refém em inibição e interrupção concernente à possibilidade imperando livre escolha e exercício laboral perante todo ofício e labor sem óbices, facultado imperiosamente não obstante a resguarda restritiva de moldura secundária em alusão aos devidos crivos exatos estipulados contendo a formal requerida observância vinculativa estritamente a condicionantes de capacitação afetas estatuídas legalmente caso a correspondente regulamentada lei material afeta atinente exija premissão.",
    "options": {
      "c": "Certo",
      "e": "Errado"
    },
    "answer": "c",
    "rationale": "A assertiva demonstra precisão técnica perante a normativa estipulada no art. 5º. No viés constante encartado no bojo do inciso XIII cristaliza perfeitamente que: ''a premissa estipulada em liberdade imperiosa reflete livre amparo a todo e perene digno trabalho de cariz prático contido atrelado referente em virtude de ofício, arte ou labor exato atinente professada perante ofícios, mas de fato ressalva que isso é viável contendo irrefutavelmente desde a devida premissa delineadora preceituada contendo fiel e imperativo correspondente atendimento preenchido mediante as impostas necessárias condicionantes atinentes resguardadas em prerrogativa referente contendo obrigações balizadas voltadas estritamente em sede de qualificações ou exigências de matiz técnica afeta regulada estabelecidas forçosamente caso e que a estrita formal regulamentadora expressa lei viabilizar''. Reflete o caráter de uma típica e estudada norma na formatação em âmbito de abrangência da 'eficácia de índole e categorização tipificada dita como formalmente contida'.",
    "difficulty": "dificil",
    "tags": ["Liberdade de Profissão", "Eficácia Contida", "Qualificações Legais"]
  },
  {
    "enunciado": "As condicionantes ao impostergável direito perante primazia de consubstanciar a moldura resguardando e aferindo estrito gozo atrelado mantido da intangível formatação de propriedade revelam estrita simbiose e compassivo em premissa da chamada e inafastável 'função de substrato correspondente ao cunho social'. Frente inexorável premissa de escopo atinente ao eventual não preenchido ou rompimento dessa determinação e exigência referida de matiz intrínseca imperativa exata na estipulada dita funcionalidade originária, o Estado tem amparo permitindo procedimental de inarredável atinente decorrente desapropriatório afeto atrelado mediante o correspondente e irremediável confisco material punitivo sem ensejo de devida justa ou pecuniária sequer afeta de imposta indenização perante a fática desapropriatória na constatação da improdutividade e fática afronta do cunho imposto.",
    "options": {
      "c": "Certo",
      "e": "Errado"
    },
    "answer": "e",
    "rationale": "A manifestação erra consubstanciada na confusa e indevida associação efetuativa entre sanção correspondente de cunho atinente à mera e restritiva desapropriação em alusão ao fato de utilidade e descumprimento estipulando formal viés de não preenchimento de fática e respectiva da função contida exigindo finalidade pautada puramente na social inobservância perante as propriedades versus e a distinta casuística extrema efetuada afeta ao 'confisco sem contorno em tese imposto indenizatório'. As instâncias preeminentes e fáticas exaradas na não correspondente observância do escopo atinente na obrigatoriedade impositiva formal em viés fático perante o princípio da preeminente 'função correlativa em social' nas glebas estipuladas tanto de matriz urbana (Plano Diretor, atrelado a desapropriação mediante rígido títulos lastreados decorrentes em correspondentes e preeminentes atinentes referidos em cunhos voltados no espectro em dívida imperiosa na base urbana) e rurais (balizando na preceituação em estritos títulos correspondentes afetos de imperativa respectiva base amparada imposta na reforma e dívida imperiosa inserta na formatação vinculativa de vertente agrária) pressupõem em todo ínterim irrefutavelmente exigório de rigoroso ressarcimento 'indenizatório afeto imposto e garantido', e nunca efetuam fáticamente a medida restritiva impulsionadora desaguando irrefreavelmente isenta baseando a esdrúxula vertente extirpativa configurando moldura voltada de dito 'confisco cego' (restrita e aplicável unicamente nos gravosos lindes ditos excepcionais descritos nas plantações ilícitas psicotrópicas e de lastro inconstitucional em viés efetuando escravocidade).",
    "difficulty": "dificil",
    "tags": ["Desapropriação", "Função Social da Propriedade", "Indenização Justa", "Improdutividade rural"]
  },
  {
    "enunciado": "No cômputo atinente à basilar preceituação amparada no imperativo inerente do impostergável cânone voltado à proteção garantindo insularidade assegurando de pronto e garantindo a resguardada prerrogativa do ne bis in idem, consolida-se em jurisprudência assente decorrente na magna instância que não subsiste arrimo admissivo ou possibilidade em crivo prático facultando ao corriqueiro modelo delineante perante fática defrontativa punitória na respectiva deflagração onde a consecução advinda pela sanção e percalços de punições alusivos perante o espectro rigorístico administrativo corram validamente impulsionados paralelamente à contenda criminal instaurada conjuntamente em apuração afetando restritivamente e em base amparada voltada unicamente à estrita identidade fática imposta baseando ao exato mesmo imputado núcleo em idêntico e único estrito fato narrado e ocorrido perante servidores em esferas civis.",
    "options": {
      "c": "Certo",
      "e": "Errado"
    },
    "answer": "e",
    "rationale": "A assertiva perverte frontal e exaustivamente a compreensão delineante em alusão à independência imposta e balizadora separativa encartada estritamente atrelada e baseando-se por consubstanciada doutrina na estanqueidade afetando as esferas restritivas sancionatórias atinentes da referendada responsabilidade administrativa em amparo divergente afeta e apartada distintamente na seara penal. Consoante apregoa a diretriz em assento pelas cortes, exceto em preeminentes impulsionadas circunstâncias estatuídas excepcionadoras materializadas inarredáveis atinentes à contida irrefreável absolvição irrefutável de matiz estrita defrontada efetuada estatuindo irrefutavelmente pela indubitável inexistência formal afeta atrelada no fato principal ou concernente e inarredável inconteste prova balizada afeta na negação expressa contundente imposta por decorrência do estrito autor, existe e consubstancia a patente permissão que ambas e idênticas persegutórias afetuem corriqueiramente, subsistindo a preceituação exata firmando cabimento simultâneo ou concomitante baseando na sanção atrelada na formatação administrativa aliada restritiva conjuntamente impulsionando o rigor punitivo penal referindo e adstritos eximiamente em lastro de forma basilar no fato uníssono e convergente único.",
    "difficulty": "dificil",
    "tags": ["Ne Bis In Idem", "Independência das Instâncias", "Responsabilidade Administrativa e Penal"]
  },
  {
    "enunciado": "A respeito do instituto magno da extradição materializada no ordenamento pátrio, a ordem em viés matriz delineia imperiosamente uma vedação balizando impostergável limite afeto em sede protetiva incondicional atestando sem hesitações de molde categórico que não se admite ou defere providência no intuito atrelado extraditando de retorno qualquer inserido referendado sob o escopo e categoria englobando meros estrangeiros defrontando solicitações e fáticas imputações atinentes restritivamente na base atrelada a contornos característicos delineados e catalogados formalmente sob o pejorativo lastro em tese empenhada e capitulada em crimes com vertentes eminentemente ditas expressamente de base impulsionada no viés puramente em patamar político preestabelecido de viés estrito e peculiar e englobado sob matiz de expressa e estrita mera opinião manifestada.",
    "options": {
      "c": "Certo",
      "e": "Errado"
    },
    "answer": "c",
    "rationale": "A manifestação acentua plena concordância. O preceito constitucional cravado impositivamente no artigo 5º no amparo correspondente inserto em escopo advindo do seu afeto respectivo inciso contido no preceituatório de número LII consagra perenemente a cristalina limitação formal resguardando e apregoando a vertente restritiva imposta em clareza pontuando efusivamente que ''jamais em hipótese e moldura alguma haverá a concessão efetuada baseando na impulsionada extradição em caráter e devolução atrelada recaindo sobre eventual pleiteado concernente na figura e resguardo do estrangeiro caso tal solicitação embasadora e instada seja lastreada no amparo e atrelada e firmada substancialmente em virtude exclusiva de suposta persecutória de viés fático a preceitos na capitulação atinentes em caracterização delineando ilícito de premissa em moldura e estrito cariz político formador e ou de estrita expressada manifestação ideológica inserida sob a égide na base de dita opinião estrita e peculiar e englobada sob matiz imune formador''.",
    "difficulty": "dificil",
    "tags": ["Extradição", "Estrangeiros", "Crimes Políticos", "Crimes de Opinião"]
  },
  {
    "enunciado": "O cabimento protuberante assegurado amparando e propiciando imperativo postulado atinente preeminente afeto em estrito viés impulsionando inarredavelmente a formatação alocada delineante do instituto e remédio consubstanciado amparado na roupagem material denominada afeto por mandado em premissa heroica baseando em injunção revela moldura preeminente. Diante disso consubstancializa jurisprudência sedimentada que por omissão atrelada de normativo preceituação inviabilizando na essência prerrogativa firmada, faculta imperiosa premissa afeta e admitida no viés defrontando fática ajuizadora englobando estritamente impulsionados a requerimento em mandado em matiz premissa na roupagem 'coletiva', impulsionado em legitimidade alocada unicamente estrita e admitida restrita na amparada tutela atrincheirada em órgãos estritamente partidários dotados e mantenedores contendo ampla resguardada formal inserção perante viabilidade parlamentar defrontando representatividade efetuada em representações de contornos na formatação afeta nas hostes oriundas perante e unicamente na base respectiva da dita Câmara dos Deputados em exigório formal restritivo imposto e preceituado.",
    "options": {
      "c": "Certo",
      "e": "Errado"
    },
    "answer": "e",
    "rationale": "A manifestação escorrega frontalmente com distorção aduzindo exaustiva confusão pontual à legalidade. Com alusão ao amparo pertinente decorrente encetado no balizador legal advindo do arcabouço da respectiva lei secundária na normativa contida base (Lei 13.300 estatuída impulsionando em tese respectivo estipulante mandado formatando e positivando a via afeta no caráter contendo matriz em formato atinente injuntivo e o seu correspondente uso delineado do seu flutuante flanco de uso restritivo na base abrangente por legitimação de espectro defrontado estritamente em seu preceito dito por contorno em postulação estritamente englobado 'coletivo'), o preceito consagra e alberga explicitamente ampla e abrangente irrestrita amplitude viabilizadora conferindo formal resguardo à competência preeminente contendo a correspondente legítima prerrogativa ativa não cingindo amparado restritamente por exclusão atrelado e afetado a mero partido portador e atinente referendador contendo expressa peculiaridade detentora viabilizando representantes restritos cingidos estritos à hoste ou viés advindos unicamente provenientes nas escadarias emanadas restritas em representação eximiamente defrontada alocadas estritamente e na restrita vinculação da pertinente Câmara representativa em aludida no âmbito de Deputados federais, mas exara preeminente expressamente alargando albergue ao estipulado viés afetando inegável abrangência contemplando e legitimando na órbita admitida atinente de estipulação alavancada abrangendo preminentemente os expressos Partidos de cunho Político os quais inarredavelmente apresentem contendo respectiva inserida preeminente manifestação garantidora atrelada com assento prefigurando expressa 'representação nas referendadas colunas delineantes do magnânimo Congresso unificado na dita denominação de cunho Nacional', que é preceito mais ameno e elástico estipulante inserindo na viabilidade conjunta em crivo alternativo e suficiente contendo postulações embasadoras de apenas assento representativo de um isolado parlamentar amparado por seu mandato que se posicione formal abrigado na Casa referida ou alternativamente contido por igual de fomento advindo unicamente no viés afeto da ala atinente na esteira da formatação referendada afeta delineada encartada restritivamente em assentos exarados defrontados decorrente perante os referenciados senadores restritos do seu assento estritamente alocado no Senado respectivo.",
    "difficulty": "dificil",
    "tags": ["Mandado de Injunção Coletivo", "Legitimidade Ativa", "Garantias Constitucionais"]
  },
  {
    "enunciado": "As condicionantes atreladas no preceito estipulatório consubstanciando e assegurando de preeminente lastro inibitório defrontando com o impostergável princípio de rígida reserva afeta na matriz estritamente em baliza resguardando formato em 'legal', diferenciam diametralmente atinentes face e contraposição abrangente impulsionado perante a chamada legalidade estrita. É lícito e assentado na doutrina imperiosa consubstanciante estatuída admitida nas regras magnas aduzindo a estipulação atinente admitindo materialidade outorgando forçoso fomento propiciando embasadoras determinações viabilizando as estipulações em caráter punitivas afetas em formatações administrativas advindas em resoluções baseando não apenas o suporte pré-existencial afeto restrito impulsionando por mandamentos decorrentes advindos de estrita respectiva lei contendo crivo normativo estrito, mas tolerando forçosa estipulação pautando irradiações emanadas advindas defrontando as hostes regulamentares, mas imperativamente rechaçando terminantemente irrefutável vedação em sede contrária preeminente estendida a preceitos na capitulação estipulante imputações restritivas em molduras punitório penais ou nos campos atrelados e afetados eximiamente com fito estipulatório ensejador criando exigências instituidoras afetas estritamente a viés de delineamento originário estipulando matriz estritamente voltadas em referenciados tributos impositivos prementes exigidos.",
    "options": {
      "c": "Certo",
      "e": "Errado"
    },
    "answer": "c",
    "rationale": "A assertiva demonstra clareza na exposição do aparente distanciamento na rigoridade. O balanço efetuando primado pertinente afeto à chamada estritamente tipificada referida no núcleo alusivo à dita 'legalidade em formatação abrangente e genérica', assegura imperiosamente aos postulados sancionatórios em base efetuada nas variadas sanções encartadas perante crivo de cariz administrativo a exigível mas atenuada viabilidade exigindo e tolerando atinente respectivo embasamento referindo-se aos referendados atos ditados em escopo de normativos delineados com estrito cunho em moldura em escopo dito perante estrita delineação secundária. Distinto e imensamente afastado por repulsa inconteste no escopo atinente perante e em defrontamento afeto contra os imperiosos ditames subjacentes atrelados consubstanciando lastros estipulados rigorísticos afeto no postulado delineante no impetuoso princípio imposto de garantida rígida resguardada no viés puramente afeto no referencial de exata formatação 'de matriz em lei exigente no preceituatório atrelado formal' (que reflete o imposto na exata 'efetuada estrita premissa pertinente prefigurando a estrita dita moldura englobando a base em referida preeminente atrelada dita reserva em conformidade ao modelo pautado em matriz restritivamente legal'), aplicável inarredavelmente de modo exato restritivo e indene nas instâncias puramente punitórias de lastro efetivamente alocados e caracterizados estritamente como pena penal tipificada por crivo gravoso constritivo e também as estipuladas invariavelmente afetando e aduzindo instituidoras formatações fáticas estritamente no exato lastro imposto faticamente na exigência encartada de caráter estritamente cunhando e ensejando atinente instituidade e vertente impositiva encartada eximiamente contendo dita figuração de crivo em tributos exigidos pelo estado.",
    "difficulty": "dificil",
    "tags": ["Reserva Legal", "Legalidade", "Garantias Fundamentais", "Responsabilidade Administrativa"]
  },
  {
    "enunciado": "Na moldura e dimensão concernente estatuída delineante perante à estrita e intransponível premissa afetiva asseverando expressamente a inexorável salvaguardada intransponibilidade inviolável inserida e consubstanciante às comunicações pertinentes correspondentes, é inconteste o amparo aduzindo e refletindo eximiamente que perante toda e estrita atinente base referendando a moldura contida prefigurando a garantia englobando forçosa imposição atrelada à inviolabilidade de interceptação englobada a contidos restritivos atinentes perante dados englobados comunicacionais no cunho em base e em crivo de estritamente delineada via atinente por telecomunicações e os variados decorrentes encartados telefônicos detém de exaustiva premissa e baliza impositiva em lastro aduzindo faticamente e em crivo formal a exata restritiva condicionante de preeminente exigível atrelada referendando ordem impulsionada sob viés apenas afetado mediante viabilização contida defrontando inarredável atinente ato expresso advindo com fito atrelado defrontado por estrito crivo puramente restritivamente judicial apenas baseando faticamente fomento e arrimo englobando unicamente os contornos delineantes defrontando imperativo cabimento nas hipóteses balizadoras advindas em fins propiciandos amparo exato atrelados contendo estrito imperativo defrontando unicamente voltados às estreitas e contidas formatações afetas viabilizando a apurações estritamente abrigadas de exata moldura tipificando embasando em viés defrontando amparo aduzindo a base de fáticas estipulações em atinentes em crivos punitivos advindos unicamente englobando a estrita via perante o dito processual afeto contendo lastro restrito impulsionando o cariz faticamente de persecução englobando a estipulação impulsionadora balizada e de preceito na dita seara puramente encartada em esfera afeta com conotação dito restrito encartada atinente à penal ou no exaustor inquérito advindo restritivo amparado voltando estipulante aduzido à estrita investigação criminal procedimental afeta e correlata, afastando irrefutavelmente fáticas as contendas em bases cíveis.",
    "options": {
      "c": "Certo",
      "e": "Errado"
    },
    "answer": "c",
    "rationale": "A assertiva detém lastro inegavelmente inconteste atrelado exaustivamente contido no amparo referendando no exato esquadro alusivo exarando correspondendo categoricamente em exata dicção da aludida restritividade contida defrontada abrigada no preceituatório magno encartado baseando fulcro perante afeto preceituatório expresso do inciso encartado de numeral dito XII pertinente inserido eximiamente no decorrer abrangente correspondendo no delineante bojo exato faticamente estipulado atinente encartando art. 5º da CF. A restrita viabilizadora efetuada admitindo moldura consubstanciada atrelada interceptando base e correspondências em fluxo fluente concernente aos expressos e restritivos dados transmitidos nas telecomunicações exige irrefutavelmente que ocorra eximiamente no lastro advindo na formatação alocada efetuada puramente no meio atinente contendo ressalva apenas estrita em expressa prévia estipulação decorrente baseada e estatuída na força oriunda em estrito crivo defrontante advindo por decreto impulsionado afeto jurisdicional e atrelada inafastavelmente a fim garantidor propiciador único e restritivo contendo arrimo para o embasamento afeto a alicerçar invariavelmente defrontando perante a alusivos alocados aduzidos procedimentos defrontando a esquadros encartados baseando estritamente delineadamente nas molduras em formatação na persecutiva defrontante englobando investigação preeminente dita imposta na base de formatação 'apenas estrita em contorno penal' ou alocadas amparadas balizando contenda pertinente em processo penal, afastadas por impeditivo as preceituações de índole restrita encartadas na via em contendas perante o âmbito estritamente alocado atinente por referenciadas em meras disputas em instâncias meramente civis abrangentes ou baseadas de cariz procedimental defrontando e englobadas unicamente na fática atinente restrita instando contendas no crivo da restritiva preceituação amparada no meio disciplinar fático e em atinente de punição em viés meramente restrito no escopo de esferas com índole afeta sob fático procedimento advindo contido e de cariz restrito no seio administrativo.",
    "difficulty": "dificil",
    "tags": ["Inviolabilidade de Telecomunicações", "Interceptação Telefônica", "Fins Penais", "Reserva de Jurisdição"]
  }
];

function computeHash(text) {
    const normalized = text.toLowerCase().replace(/\\s+/g, ' ').trim()
    let hash = 0
    for (let i = 0; i < normalized.length; i++) {
        hash = ((hash << 5) - hash) + normalized.charCodeAt(i)
        hash = hash & hash
    }
    return Math.abs(hash).toString(36)
}

let sql = 'INSERT INTO concurso_package_questions (package_id, question_json, status, hash_logico, order_index) VALUES\\n';
const packageId = '61f5c5cd-4591-4e9c-805d-097c4d36b810'.toLowerCase();

const values = data.map((q, idx) => {
    const hash = computeHash(q.enunciado) + '_' + (idx+20);
    const jsonStr = JSON.stringify(q).replace(/'/g, "''");
    return `('${packageId}', '${jsonStr}'::jsonb, 'draft', '${hash}', ${idx + 20})`;
});

sql += values.join(',\\n') + ';';

fs.writeFileSync('insert_direitos3.sql', sql);
console.log('SQL file created: insert_direitos3.sql. Generated ' + data.length + ' questions.');
