INSERT INTO assuntos (nome, specialty_id, subspecialty_id, tema) VALUES 
('Clínica Médica', 'clinica-medica', NULL, NULL),
('Clínica Médica - Cardiologia', 'clinica-medica', 'cardiologia', 'Cardiologia'),
('Clínica Médica - Endocrinologia', 'clinica-medica', 'endocrinologia', 'Endocrinologia'),
('Clínica Médica - Gastroenterologia', 'clinica-medica', 'gastroenterologia', 'Gastroenterologia'),
('Clínica Médica - Geriatria', 'clinica-medica', 'geriatria', 'Geriatria'),
('Clínica Médica - Hematologia', 'clinica-medica', 'hematologia', 'Hematologia'),
('Clínica Médica - Infectologia', 'clinica-medica', 'infectologia', 'Infectologia'),
('Clínica Médica - Nefrologia', 'clinica-medica', 'nefrologia', 'Nefrologia'),
('Clínica Médica - Pneumologia', 'clinica-medica', 'pneumologia', 'Pneumologia'),
('Clínica Médica - Reumatologia', 'clinica-medica', 'reumatologia', 'Reumatologia'),
('Clínica Médica - Oncologia Clínica', 'clinica-medica', 'oncologia-clinica', 'Oncologia Clínica'),
('Cirurgia Geral', 'cirurgia-geral', NULL, NULL),
('Pediatria', 'pediatria', NULL, NULL),
('Pediatria - Neonatologia', 'pediatria', 'neonatologia', 'Neonatologia'),
('Pediatria - Cardiologia Pediátrica', 'pediatria', 'cardiologia-pediatrica', 'Cardiologia Pediátrica'),
('Pediatria - Endocrinologia Pediátrica', 'pediatria', 'endocrinologia-pediatrica', 'Endocrinologia Pediátrica'),
('Pediatria - Gastroenterologia Pediátrica', 'pediatria', 'gastroenterologia-pediatrica', 'Gastroenterologia Pediátrica'),
('Pediatria - Nefrologia Pediátrica', 'pediatria', 'nefrologia-pediatrica', 'Nefrologia Pediátrica'),
('Pediatria - Pneumologia Pediátrica', 'pediatria', 'pneumologia-pediatrica', 'Pneumologia Pediátrica'),
('Pediatria - Terapia Intensiva Pediátrica', 'pediatria', 'terapia-intensiva-pediatrica', 'Terapia Intensiva Pediátrica'),
('Pediatria - Alergia e Imunologia Pediátrica', 'pediatria', 'alergia-imunologia-pediatrica', 'Alergia e Imunologia Pediátrica'),
('Ginecologia e Obstetrícia', 'ginecologia-obstetricia', NULL, NULL),
('Ginecologia e Obstetrícia - Reprodução Humana', 'ginecologia-obstetricia', 'reproducao-humana', 'Reprodução Humana'),
('Ginecologia e Obstetrícia - Medicina Fetal', 'ginecologia-obstetricia', 'medicina-fetal', 'Medicina Fetal'),
('Ginecologia e Obstetrícia - Endoscopia Ginecológica', 'ginecologia-obstetricia', 'endoscopia-ginecologica', 'Endoscopia Ginecológica'),
('Ginecologia e Obstetrícia - Uroginecologia', 'ginecologia-obstetricia', 'uroginecologia', 'Uroginecologia'),
('Medicina de Família e Comunidade', 'medicina-familia-comunidade', NULL, NULL),
('Alergia e Imunologia', 'alergia-imunologia', NULL, NULL),
('Angiologia', 'angiologia', NULL, NULL),
('Cardiologia', 'cardiologia-clinica', NULL, NULL),
('Dermatologia', 'dermatologia', NULL, NULL),
('Endocrinologia e Metabologia', 'endocrinologia-metabologia', NULL, NULL),
('Gastroenterologia', 'gastroenterologia-clinica', NULL, NULL),
('Geriatria', 'geriatria-clinica', NULL, NULL),
('Hematologia e Hemoterapia', 'hematologia-hemoterapia', NULL, NULL),
('Infectologia', 'infectologia-clinica', NULL, NULL),
('Nefrologia', 'nefrologia-clinica', NULL, NULL),
('Neurologia', 'neurologia', NULL, NULL),
('Neurologia - Neurologia Pediátrica', 'neurologia', 'neurologia-pediatrica', 'Neurologia Pediátrica'),
('Neurologia - Neurofisiologia Clínica', 'neurologia', 'neurofisiologia-clinica', 'Neurofisiologia Clínica'),
('Oncologia Clínica', 'oncologia-clinica-espec', NULL, NULL),
('Pneumologia', 'pneumologia-clinica', NULL, NULL),
('Psiquiatria', 'psiquiatria', NULL, NULL),
('Psiquiatria - Psiquiatria da Infância e Adolescência', 'psiquiatria', 'psiquiatria-infancia-adolescencia', 'Psiquiatria da Infância e Adolescência'),
('Psiquiatria - Dependência Química', 'psiquiatria', 'dependencia-quimica', 'Dependência Química'),
('Psiquiatria - Psicogeriatria', 'psiquiatria', 'psicogeriatria', 'Psicogeriatria'),
('Psiquiatria - Psiquiatria Forense', 'psiquiatria', 'psiquiatria-forense', 'Psiquiatria Forense'),
('Reumatologia', 'reumatologia-clinica', NULL, NULL),
('Medicina do Trabalho', 'medicina-trabalho', NULL, NULL),
('Medicina Esportiva', 'medicina-esportiva', NULL, NULL),
('Medicina Física e Reabilitação', 'medicina-fisica-reabilitacao', NULL, NULL),
('Medicina Preventiva e Social', 'medicina-preventiva-social', NULL, NULL),
('Genética Médica', 'genetica-medica', NULL, NULL),
('Medicina Intensiva', 'medicina-intensiva', NULL, NULL),
('Medicina de Emergência', 'medicina-emergencia', NULL, NULL),
('Medicina de Emergência - Emergências Clínicas', 'medicina-emergencia', 'emergencias-clinicas', 'Emergências Clínicas'),
('Medicina de Emergência - Emergências Cardiovasculares', 'medicina-emergencia', 'emergencias-cardiovasculares', 'Emergências Cardiovasculares'),
('Medicina de Emergência - Trauma', 'medicina-emergencia', 'trauma', 'Trauma'),
('Medicina de Emergência - Emergências Neurológicas', 'medicina-emergencia', 'emergencias-neurologicas', 'Emergências Neurológicas'),
('Medicina do Sono', 'medicina-sono', NULL, NULL),
('Cirurgia Cardiovascular', 'cirurgia-cardiovascular', NULL, NULL),
('Cirurgia da Mão', 'cirurgia-mao', NULL, NULL),
('Cirurgia de Cabeça e Pescoço', 'cirurgia-cabeca-pescoco', NULL, NULL),
('Cirurgia do Aparelho Digestivo', 'cirurgia-aparelho-digestivo', NULL, NULL),
('Cirurgia Pediátrica', 'cirurgia-pediatrica', NULL, NULL),
('Cirurgia Plástica', 'cirurgia-plastica', NULL, NULL),
('Cirurgia Torácica', 'cirurgia-toracica', NULL, NULL),
('Cirurgia Vascular', 'cirurgia-vascular', NULL, NULL),
('Coloproctologia', 'coloproctologia', NULL, NULL),
('Mastologia', 'mastologia', NULL, NULL),
('Neurocirurgia', 'neurocirurgia', NULL, NULL),
('Oftalmologia', 'oftalmologia', NULL, NULL),
('Ortopedia e Traumatologia', 'ortopedia-traumatologia', NULL, NULL),
('Ortopedia e Traumatologia - Cirurgia do Joelho', 'ortopedia-traumatologia', 'cirurgia-joelho', 'Cirurgia do Joelho'),
('Ortopedia e Traumatologia - Cirurgia do Quadril', 'ortopedia-traumatologia', 'cirurgia-quadril', 'Cirurgia do Quadril'),
('Ortopedia e Traumatologia - Cirurgia da Coluna', 'ortopedia-traumatologia', 'cirurgia-coluna', 'Cirurgia da Coluna'),
('Ortopedia e Traumatologia - Cirurgia do Ombro e Cotovelo', 'ortopedia-traumatologia', 'cirurgia-ombro-cotovelo', 'Cirurgia do Ombro e Cotovelo'),
('Ortopedia e Traumatologia - Ortopedia Pediátrica', 'ortopedia-traumatologia', 'ortopedia-pediatrica', 'Ortopedia Pediátrica'),
('Ortopedia e Traumatologia - Medicina do Esporte', 'ortopedia-traumatologia', 'medicina-esporte-orto', 'Medicina do Esporte'),
('Otorrinolaringologia', 'otorrinolaringologia', NULL, NULL),
('Urologia', 'urologia', NULL, NULL),
('Anestesiologia', 'anestesiologia', NULL, NULL),
('Patologia', 'patologia', NULL, NULL),
('Patologia Clínica / Medicina Laboratorial', 'patologia-clinica', NULL, NULL),
('Radiologia e Diagnóstico por Imagem', 'radiologia', NULL, NULL),
('Radioterapia', 'radioterapia', NULL, NULL),
('Medicina Nuclear', 'medicina-nuclear', NULL, NULL);
